FROM node:20-bookworm-slim AS builder
WORKDIR /web
COPY package.json vite.config.js ./
COPY index.html ./
COPY src ./src
COPY public ./public
RUN npm install && npm run build

FROM nginx:alpine
COPY --from=builder /web/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx","-g","daemon off;"]
